; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
upload_speed = 460800
;upload_port = /dev/cu.usbserial-A5069RR4
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = release
build_flags =
	-D ELEGANTOTA
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D WEBSERIAL
	-D WIFI
	-D NTP
;	-D DEEPSLEEP
lib_compat_mode = strict
lib_ldf_mode = deep
lib_deps = 
;	https://github.com/ESP32Async/AsyncTCP#v3.4.9
;	https://github.com/ESP32Async/ESPAsyncWebServer#v3.8.1
	https://github.com/ESP32Async/AsyncTCP
	https://github.com/ESP32Async/ESPAsyncWebServer
	https://github.com/ayushsharma82/ElegantOTA
;	https://github.com/ayushsharma82/WebSerial
	/home/wjquigs/nfs/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip
	bblanchon/ArduinoJson@^7.2.0
	arduino-libraries/NTPClient
	thijse/ArduinoLog
	sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor
	sparkfun/SparkFun I2C Mux Arduino Library
	adafruit/Adafruit MCP23017 Arduino Library
	https://github.com/DCC-EX/DCCEXProtocol
	https://github.com/wjquigs11/movingAvg
	https://github.com/mairas/ReactESP

[env:diamond]
extends = env:esp32dev
build_flags = 
    -D DIAMOND
	-D LED_BUILTIN=2

[env:turnout]
extends = env:esp32dev
build_flags = 
    -D TURNOUT
	-D LED_BUILTIN=2

[env:ota]
extends = env:esp32doit-devkit-v1
upload_protocol = espota
upload_port = 192.168.68.53
upload_flags = 
	--port=3232